# Generated by Django 3.2.25 on 2024-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=15)),
                ('niveau', models.CharField(max_length=10)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
