# Generated by Django 3.2.25 on 2024-07-09 19:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('vues', models.PositiveBigIntegerField(default=0)),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('prerequis', models.CharField(default='aucune connaissance nécessaire', max_length=255)),
                ('estimation', models.CharField(default='9 heures pour terminer le cours', max_length=255)),
                ('detail_estimation', models.CharField(default='3 semaines à 3 heures par semaine', max_length=255)),
                ('a_propos', models.CharField(default='description du cours', max_length=511)),
                ('image', models.ImageField(default='image1.jpeg', upload_to='images_upload')),
            ],
            options={
                'db_table': 'Cours',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Matiere',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Niveau',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=30)),
                ('type_de_contenu', models.CharField(choices=[('pdf', 'PDF'), ('lien', 'LIEN HYPERTEXTE'), ('video', 'VIDEO')], max_length=5)),
                ('contenu_pdf', models.FileField(default='fichier.pdf', upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('contenu_video', models.FileField(default='video.mp4', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('contenu_lien', models.URLField()),
            ],
            options={
                'db_table': 'Ressource',
                'ordering': ['titre'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_enseignant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('num_ordre', models.IntegerField(default=0)),
                ('type_de_contenu', models.CharField(choices=[('pdf', 'PDF'), ('texte', 'TEXTE'), ('video', 'VIDEO')], max_length=5)),
                ('contenu_texte', tinymce.models.HTMLField(default='contenu')),
                ('contenu_pdf', models.FileField(default='fichier.pdf', upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('contenu_video', models.FileField(default='video.mp4', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('description', models.CharField(max_length=255)),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours_lecon', to='app1.cours')),
            ],
            options={
                'db_table': 'Lecon',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.CharField(default='valeur', max_length=255, primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_inscription', to='app1.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleve_inscription', to='app1.userprofile')),
            ],
            options={
                'db_table': 'Inscription',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GrandsPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenu_texte', models.TextField(default='contenu')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grandsp_cours', to='app1.cours')),
            ],
            options={
                'db_table': 'GrandsPoint',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='instructeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructeur_cours', to='app1.userprofile'),
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_cours', to='app1.matiere'),
        ),
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveau_cours', to='app1.niveau'),
        ),
    ]
